services:
  - type: web
    name: AI_Powered_Mock_Interview_Platform
    env: node
    plan: free
    region: oregon
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: CLIENT_URL
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: GEMINI_API_KEY
        sync: false
      - key: MURF_API_KEY
        sync: false
      - key: ASSEMBLYAI_API_KEY
        sync: false
